### PR TITLE
Make resolution cross-env in filesystem plugin and base package

### LINKED ISSUE #1094: [Bug] 7.0.4 Could not find a route for the "index" page of your site! This is required. Please create a page or specify a route and template for this page.
error message: `Could not find a route for the "index" page of your site! This is required. Please create a page or specify a route and template for this page.`. While there is a index page in ./src/pages and the plugin for this is installed.

This happens to the default typescript template (which is missing `"react-static-plugin-typescript": "^7.0.0"` & typescript, on another note).

steps to reproduce:
1. react-static create 
2. select typescript
3. install dependencies

### Environment
```

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-2700K CPU @ 3.50GHz
    Memory: 5.50 GB / 15.69 GB
  Binaries:
    Node: 11.11.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.15.2 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.7.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.1.0
    Internet Explorer: 11.0.17763.1
  npmPackages:
    react: ^16.8.2 => 16.8.6
    react-dom: ^16.8.2 => 16.8.6
    react-static: ^7.0.0 => 7.0.5
    react-static-plugin-reach-router: ^7.0.0 => 7.0.0
    react-static-plugin-sitemap: ^7.0.0 => 7.0.0
    react-static-plugin-source-filesystem: ^7.0.0 => 7.0.0
    react-static-plugin-typescript: ^7.0.0 => 7.0.0

```

### Expected Behavior
No error

### LINKED ISSUE #1122: [Bug] 7.0.7 Could not find a route for the "index" page of your site!
### Reporting a bug?

This is the first I have worked with `react-static`. I ran `npm install -g react-static` and `react-static create`, created a directory using the basic template, changed into the new directory, and tried all of the following:

- `npx react-static start`
- `react-static start`
- `npx react-static build`

I get the same error each time.

```
  Error: Could not find a route for the "index" page of your site! This is required. Please create a page or specify a route and template for this page.

  - getRoutes.js:38 _callee$
    [v11.11.0]/[react-static]/src/static/getRoutes.js:38:13

  - runtime.js:45 tryCatch
    [v11.11.0]/[react-static]/[regenerator-runtime]/runtime.js:45:40

  - runtime.js:271 Generator.invoke [as _invoke]
    [v11.11.0]/[react-static]/[regenerator-runtime]/runtime.js:271:22

  - runtime.js:97 Generator.prototype.(anonymous function) [as next]
    [v11.11.0]/[react-static]/[regenerator-runtime]/runtime.js:97:21

  - asyncToGenerator.js:3 asyncGeneratorStep
    [v11.11.0]/[react-static]/[@babel]/runtime/helpers/asyncToGenerator.js:3:24

  - asyncToGenerator.js:25 _next
    [v11.11.0]/[react-static]/[@babel]/runtime/helpers/asyncToGenerator.js:25:9

  - next_tick.js:81 processTicksAndRejections
    internal/process/next_tick.js:81:5
```

This appears to be a duplicate of #1094, but in that bug it was asked to open a new issue if there were new issues and that is what I am facing. The environment, repro steps, and solution of removing `path.resolve` in `static.config.js` all match my case.

Thank you for your time.

### Environment

```
  System:                                                     
    OS: Windows 10                                            
    CPU: (4) x64 Intel(R) Core(TM) i7-6650U CPU @ 2.20GHz     
    Memory: 2.85 GB / 15.93 GB                                
  Binaries:                                                   
    Node: 11.11.0 - C:\Program Files\nodejs\node.EXE          
    npm: 6.7.0 - C:\Program Files\nodejs\npm.CMD              
  Browsers:                                                   
    Edge: 44.17763.1.0                                        
    Internet Explorer: 11.0.17763.1                           
  npmPackages:                                                
    react: ^16.8.2 => 16.8.6                                  
    react-dom: ^16.8.2 => 16.8.6                              
    react-static: ^7.0.0 => 7.0.7                             
    react-static-plugin-reach-router: ^7.0.0 => 7.0.7         
    react-static-plugin-sitemap: ^7.0.0 => 7.0.0              
    react-static-plugin-source-filesystem: ^7.0.0 => 7.0.0    
```

### Steps to Reproduce the problem

1.  `npm i -g react-static`
2.  `react-static create`
3.  select basic template
4.  cd into new project directory
5. `react-static start`

### Expected Behavior

No error, a working build out of the box.

### LINKED ISSUE #1123: [Bug] TypeError: Failed exporting HTML for URL Cannot convert undefined or null to object
### Reporting a bug?

Fresh install of React Static using the "basic" template. Tried running `npm build`
```
D:\Documents\Repositories\react-static\test-site>npm run build

> react-static-example-basic@ build D:\Documents\Repositories\react-static\test-site
> react-static build

Bundling application for Production...

Cleaning dist...
[✓] Dist cleaned (0.5s)
Cleaning artifacts...
[✓] Artifacts cleaned
Building Routes...
Importing routes from directory...
[✓] Routes Built (0.8s)
Building Templates...
[✓] Templates Built
Copying public directory...
[✓] Public directory copied
Bundling App...
[✓] App Bundled (14.8s)
Fetching Site Data...
[✓] Site Data Downloaded
Fetching Route Data...
[==========================================================================================] 107/107 100% 17833/s 0.0s
[✓] Route Data Downloaded (0.2s)
Exporting HTML across 8 threads...
  TypeError: Failed exporting HTML for URL D:/Documents/Repositories/react-static/test-site/src/pages/blog (../src/pages  /blog.js): Cannot convert undefined or null to object

  - Function.keys

  - Routes.js:38 keys
    [test-site]/[react-static]/src/browser/components/Routes.js:38:14

  - react-dom-server.node.production.min.js:26 ya
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:26:264

  - react-dom-server.node.production.min.js:29 Object.useState
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:29:82

  - react.production.min.js:23 useState
    [test-site]/[react]/cjs/react.production.min.js:23:312

  - Routes.js:27 RoutesInner
    [test-site]/[react-static]/src/browser/components/Routes.js:27:3

  - react-dom-server.node.production.min.js:33 c
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:33:501

  - react-dom-server.node.production.min.js:36 Sa
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:36:1

  - react-dom-server.node.production.min.js:41 a.render
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:41:467

  - react-dom-server.node.production.min.js:41 a.read
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:41:58

  - react-dom-server.node.production.min.js:53 renderToString
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:53:83

  - exportRoute.js:137 renderToStringAndExtract
    [test-site]/[react-static]/src/static/exportRoute.js:137:21

  - exportRoute.js:192 renderToStringAndExtract
    [test-site]/[react-static]/src/static/exportRoute.js:192:15

  - runtime.js:45 tryCatch
    [test-site]/[regenerator-runtime]/runtime.js:45:40

  - runtime.js:271 Generator.invoke [as _invoke]
    [test-site]/[regenerator-runtime]/runtime.js:271:22

  - runtime.js:97 Generator.prototype.(anonymous function) [as next]
    [test-site]/[regenerator-runtime]/runtime.js:97:21

  - asyncToGenerator.js:3 asyncGeneratorStep
    [test-site]/[@babel]/runtime/helpers/asyncToGenerator.js:3:24

  - asyncToGenerator.js:25 _next
    [test-site]/[@babel]/runtime/helpers/asyncToGenerator.js:25:9


  - next_tick.js:188 process._tickCallback
    internal/process/next_tick.js:188:7


  Error:

  TypeError: Failed exporting HTML for URL 404 (../node_modules/react-static/lib/browser/components/Default404): Cannot   convert undefined or null to object

  - Function.keys

  - Routes.js:38 keys
    [test-site]/[react-static]/src/browser/components/Routes.js:38:14

  - react-dom-server.node.production.min.js:26 ya
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:26:264

  - react-dom-server.node.production.min.js:29 Object.useState
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:29:82

  - react.production.min.js:23 useState
    [test-site]/[react]/cjs/react.production.min.js:23:312

  - Routes.js:27 RoutesInner
    [test-site]/[react-static]/src/browser/components/Routes.js:27:3

  - react-dom-server.node.production.min.js:33 c
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:33:501

  - react-dom-server.node.production.min.js:36 Sa
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:36:1

  - react-dom-server.node.production.min.js:41 a.render
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:41:467

  - react-dom-server.node.production.min.js:41 a.read
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:41:58

  - react-dom-server.node.production.min.js:53 renderToString
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:53:83

  - exportRoute.js:137 renderToStringAndExtract
    [test-site]/[react-static]/src/static/exportRoute.js:137:21

  - exportRoute.js:192 renderToStringAndExtract
    [test-site]/[react-static]/src/static/exportRoute.js:192:15

  - runtime.js:45 tryCatch
    [test-site]/[regenerator-runtime]/runtime.js:45:40

  - runtime.js:271 Generator.invoke [as _invoke]
    [test-site]/[regenerator-runtime]/runtime.js:271:22

  - runtime.js:97 Generator.prototype.(anonymous function) [as next]
    [test-site]/[regenerator-runtime]/runtime.js:97:21

  - asyncToGenerator.js:3 asyncGeneratorStep
    [test-site]/[@babel]/runtime/helpers/asyncToGenerator.js:3:24

  - asyncToGenerator.js:25 _next
    [test-site]/[@babel]/runtime/helpers/asyncToGenerator.js:25:9


  - next_tick.js:188 process._tickCallback
    internal/process/next_tick.js:188:7


  TypeError: Failed exporting HTML for URL D:/Documents/Repositories/react-static/test-site/src/pages (../src/pages/inde  x.js): Cannot convert undefined or null to object

  - Function.keys

  - Routes.js:38 keys
    [test-site]/[react-static]/src/browser/components/Routes.js:38:14

  - react-dom-server.node.production.min.js:26 ya
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:26:264

  - react-dom-server.node.production.min.js:29 Object.useState
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:29:82

  - react.production.min.js:23 useState
    [test-site]/[react]/cjs/react.production.min.js:23:312

  - Routes.js:27 RoutesInner
    [test-site]/[react-static]/src/browser/components/Routes.js:27:3

  - react-dom-server.node.production.min.js:33 c
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:33:501

  - react-dom-server.node.production.min.js:36 Sa
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:36:1

  - react-dom-server.node.production.min.js:41 a.render
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:41:467

  - react-dom-server.node.production.min.js:41 a.read
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:41:58

  - react-dom-server.node.production.min.js:53 renderToString
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:53:83

  - exportRoute.js:137 renderToStringAndExtract
    [test-site]/[react-static]/src/static/exportRoute.js:137:21

  - exportRoute.js:192 renderToStringAndExtract
    [test-site]/[react-static]/src/static/exportRoute.js:192:15

  - runtime.js:45 tryCatch
    [test-site]/[regenerator-runtime]/runtime.js:45:40

  - runtime.js:271 Generator.invoke [as _invoke]
    [test-site]/[regenerator-runtime]/runtime.js:271:22

  - runtime.js:97 Generator.prototype.(anonymous function) [as next]
    [test-site]/[regenerator-runtime]/runtime.js:97:21

  - asyncToGenerator.js:3 asyncGeneratorStep
    [test-site]/[@babel]/runtime/helpers/asyncToGenerator.js:3:24

  - asyncToGenerator.js:25 _next
    [test-site]/[@babel]/runtime/helpers/asyncToGenerator.js:25:9


  - next_tick.js:188 process._tickCallback
    internal/process/next_tick.js:188:7


  TypeError: Failed exporting HTML for URL blog/post/2 (../src/containers/Post): Cannot convert undefined or null to obj  ect

  - Function.keys

  - Routes.js:38 keys
    [test-site]/[react-static]/src/browser/components/Routes.js:38:14

  - react-dom-server.node.production.min.js:26 ya
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:26:264

  - react-dom-server.node.production.min.js:29 Object.useState
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:29:82

  - react.production.min.js:23 useState
    [test-site]/[react]/cjs/react.production.min.js:23:312

  - Routes.js:27 RoutesInner
    [test-site]/[react-static]/src/browser/components/Routes.js:27:3

  - react-dom-server.node.production.min.js:33 c
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:33:501

  - react-dom-server.node.production.min.js:36 Sa
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:36:1

  - react-dom-server.node.production.min.js:41 a.render
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:41:467

  - react-dom-server.node.production.min.js:41 a.read
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:41:58

  - react-dom-server.node.production.min.js:53 renderToString
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:53:83

  - exportRoute.js:137 renderToStringAndExtract
    [test-site]/[react-static]/src/static/exportRoute.js:137:21

  - exportRoute.js:192 renderToStringAndExtract
    [test-site]/[react-static]/src/static/exportRoute.js:192:15

  - runtime.js:45 tryCatch
    [test-site]/[regenerator-runtime]/runtime.js:45:40

  - runtime.js:271 Generator.invoke [as _invoke]
    [test-site]/[regenerator-runtime]/runtime.js:271:22

  - runtime.js:97 Generator.prototype.(anonymous function) [as next]
    [test-site]/[regenerator-runtime]/runtime.js:97:21

  - asyncToGenerator.js:3 asyncGeneratorStep
    [test-site]/[@babel]/runtime/helpers/asyncToGenerator.js:3:24

  - asyncToGenerator.js:25 _next
    [test-site]/[@babel]/runtime/helpers/asyncToGenerator.js:25:9


  - next_tick.js:188 process._tickCallback
    internal/process/next_tick.js:188:7


  TypeError: Failed exporting HTML for URL / (../src/App): Cannot convert undefined or null to object

  - Function.keys

  - Routes.js:38 keys
    [test-site]/[react-static]/src/browser/components/Routes.js:38:14

  - react-dom-server.node.production.min.js:26 ya
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:26:264

  - react-dom-server.node.production.min.js:29 Object.useState
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:29:82

  - react.production.min.js:23 useState
    [test-site]/[react]/cjs/react.production.min.js:23:312

  - Routes.js:27 RoutesInner
    [test-site]/[react-static]/src/browser/components/Routes.js:27:3

  - react-dom-server.node.production.min.js:33 c
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:33:501

  - react-dom-server.node.production.min.js:36 Sa
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:36:1

  - react-dom-server.node.production.min.js:41 a.render
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:41:467

  - react-dom-server.node.production.min.js:41 a.read
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:41:58

  - react-dom-server.node.production.min.js:53 renderToString
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:53:83

  - exportRoute.js:137 renderToStringAndExtract
    [test-site]/[react-static]/src/static/exportRoute.js:137:21

  - exportRoute.js:192 renderToStringAndExtract
    [test-site]/[react-static]/src/static/exportRoute.js:192:15

  - runtime.js:45 tryCatch
    [test-site]/[regenerator-runtime]/runtime.js:45:40

  - runtime.js:271 Generator.invoke [as _invoke]
    [test-site]/[regenerator-runtime]/runtime.js:271:22

  - runtime.js:97 Generator.prototype.(anonymous function) [as next]
    [test-site]/[regenerator-runtime]/runtime.js:97:21

  - asyncToGenerator.js:3 asyncGeneratorStep
    [test-site]/[@babel]/runtime/helpers/asyncToGenerator.js:3:24

  - asyncToGenerator.js:25 _next
    [test-site]/[@babel]/runtime/helpers/asyncToGenerator.js:25:9


  - next_tick.js:188 process._tickCallback
    internal/process/next_tick.js:188:7


  TypeError: Failed exporting HTML for URL D:/Documents/Repositories/react-static/test-site/src/pages/404 (../src/pages/  404.js): Cannot convert undefined or null to object

  - Function.keys

  - Routes.js:38 keys
    [test-site]/[react-static]/src/browser/components/Routes.js:38:14

  - react-dom-server.node.production.min.js:26 ya
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:26:264

  - react-dom-server.node.production.min.js:29 Object.useState
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:29:82

  - react.production.min.js:23 useState
    [test-site]/[react]/cjs/react.production.min.js:23:312

  - Routes.js:27 RoutesInner
    [test-site]/[react-static]/src/browser/components/Routes.js:27:3

  - react-dom-server.node.production.min.js:33 c
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:33:501

  - react-dom-server.node.production.min.js:36 Sa
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:36:1

  - react-dom-server.node.production.min.js:41 a.render
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:41:467

  - react-dom-server.node.production.min.js:41 a.read
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:41:58

  - react-dom-server.node.production.min.js:53 renderToString
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:53:83

  - exportRoute.js:137 renderToStringAndExtract
    [test-site]/[react-static]/src/static/exportRoute.js:137:21

  - exportRoute.js:192 renderToStringAndExtract
    [test-site]/[react-static]/src/static/exportRoute.js:192:15

  - runtime.js:45 tryCatch
    [test-site]/[regenerator-runtime]/runtime.js:45:40

  - runtime.js:271 Generator.invoke [as _invoke]
    [test-site]/[regenerator-runtime]/runtime.js:271:22

  - runtime.js:97 Generator.prototype.(anonymous function) [as next]
    [test-site]/[regenerator-runtime]/runtime.js:97:21

  - asyncToGenerator.js:3 asyncGeneratorStep
    [test-site]/[@babel]/runtime/helpers/asyncToGenerator.js:3:24

  - asyncToGenerator.js:25 _next
    [test-site]/[@babel]/runtime/helpers/asyncToGenerator.js:25:9


  - next_tick.js:188 process._tickCallback
    internal/process/next_tick.js:188:7


  TypeError: Failed exporting HTML for URL blog/post/1 (../src/containers/Post): Cannot convert undefined or null to obj  ect

  - Function.keys

  - Routes.js:38 keys
    [test-site]/[react-static]/src/browser/components/Routes.js:38:14

  - react-dom-server.node.production.min.js:26 ya
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:26:264

  - react-dom-server.node.production.min.js:29 Object.useState
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:29:82

  - react.production.min.js:23 useState
    [test-site]/[react]/cjs/react.production.min.js:23:312

  - Routes.js:27 RoutesInner
    [test-site]/[react-static]/src/browser/components/Routes.js:27:3

  - react-dom-server.node.production.min.js:33 c
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:33:501

  - react-dom-server.node.production.min.js:36 Sa
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:36:1

  - react-dom-server.node.production.min.js:41 a.render
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:41:467

  - react-dom-server.node.production.min.js:41 a.read
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:41:58

  - react-dom-server.node.production.min.js:53 renderToString
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:53:83

  - exportRoute.js:137 renderToStringAndExtract
    [test-site]/[react-static]/src/static/exportRoute.js:137:21

  - exportRoute.js:192 renderToStringAndExtract
    [test-site]/[react-static]/src/static/exportRoute.js:192:15

  - runtime.js:45 tryCatch
    [test-site]/[regenerator-runtime]/runtime.js:45:40

  - runtime.js:271 Generator.invoke [as _invoke]
    [test-site]/[regenerator-runtime]/runtime.js:271:22

  - runtime.js:97 Generator.prototype.(anonymous function) [as next]
    [test-site]/[regenerator-runtime]/runtime.js:97:21

  - asyncToGenerator.js:3 asyncGeneratorStep
    [test-site]/[@babel]/runtime/helpers/asyncToGenerator.js:3:24

  - asyncToGenerator.js:25 _next
    [test-site]/[@babel]/runtime/helpers/asyncToGenerator.js:25:9


  - next_tick.js:188 process._tickCallback
    internal/process/next_tick.js:188:7


  TypeError: Failed exporting HTML for URL D:/Documents/Repositories/react-static/test-site/src/pages/about (../src/page  s/about.js): Cannot convert undefined or null to object

  - Function.keys

  - Routes.js:38 keys
    [test-site]/[react-static]/src/browser/components/Routes.js:38:14

  - react-dom-server.node.production.min.js:26 ya
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:26:264

  - react-dom-server.node.production.min.js:29 Object.useState
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:29:82

  - react.production.min.js:23 useState
    [test-site]/[react]/cjs/react.production.min.js:23:312

  - Routes.js:27 RoutesInner
    [test-site]/[react-static]/src/browser/components/Routes.js:27:3

  - react-dom-server.node.production.min.js:33 c
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:33:501

  - react-dom-server.node.production.min.js:36 Sa
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:36:1

  - react-dom-server.node.production.min.js:41 a.render
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:41:467

  - react-dom-server.node.production.min.js:41 a.read
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:41:58

  - react-dom-server.node.production.min.js:53 renderToString
    [test-site]/[react-dom]/cjs/react-dom-server.node.production.min.js:53:83

  - exportRoute.js:137 renderToStringAndExtract
    [test-site]/[react-static]/src/static/exportRoute.js:137:21

  - exportRoute.js:192 renderToStringAndExtract
    [test-site]/[react-static]/src/static/exportRoute.js:192:15

  - runtime.js:45 tryCatch
    [test-site]/[regenerator-runtime]/runtime.js:45:40

  - runtime.js:271 Generator.invoke [as _invoke]
    [test-site]/[regenerator-runtime]/runtime.js:271:22

  - runtime.js:97 Generator.prototype.(anonymous function) [as next]
    [test-site]/[regenerator-runtime]/runtime.js:97:21

  - asyncToGenerator.js:3 asyncGeneratorStep
    [test-site]/[@babel]/runtime/helpers/asyncToGenerator.js:3:24

  - asyncToGenerator.js:25 _next
    [test-site]/[@babel]/runtime/helpers/asyncToGenerator.js:25:9


  - next_tick.js:188 process._tickCallback
    internal/process/next_tick.js:188:7
```

### Environment

```

  System:
    OS: Windows 10
    CPU: (8) x64 AMD FX(tm)-8350 Eight-Core Processor
    Memory: 16.02 GB / 31.98 GB
  Binaries:
    Node: 8.9.4 - C:\Program Files\nodejs\node.EXE
    npm: 5.3.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.1.0
    Internet Explorer: 11.0.17763.1
  npmPackages:
    react: ^16.8.2 => 16.8.6
    react-dom: ^16.8.2 => 16.8.6
    react-static: ^7.0.0 => 7.0.7
    react-static-plugin-reach-router: ^7.0.0 => 7.0.7
    react-static-plugin-sitemap: ^7.0.0 => 7.0.0
    react-static-plugin-source-filesystem: ^7.0.0 => 7.0.0

```

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

1. Create react-static application using the "basic" template
2.  Run `npm run build`

### Expected Behavior

Built site, no errors

### PR DESCRIPTION
**Pull request by SleeplessByte**
- Makes sure it's relative to the location root, not site root
- Makes sure it's resolving paths, indepedent of file system
- Makes sure it starts with a slash in case there is no directory structure

## Description

Changes the resolution in `react-static-plugin-source-filesystem` to be cross-env compatible.

* Stop using hardcoded path separators. These are not the same across environments.
* Use `path.relative` for relative resolution instead of replace. This normalises paths first, so it works across environments.
* Cutoff the extension using `path.basename` and `path.extname`, which works across environments.
* Prefix with a slash if necessary (top-level pages)
* Change the comment to be correct: make relative to `location` root, not site root.

This works with `path.resolve(...)` and `./src/pages`.

Changes the resolution in `react-static` to be cross-env compatible.

* Throw an error if a plugin resolves a windows path (it expects POSIX paths by then)
* Use `join` whenever dealing with real paths
* Add tests for the behaviour above

Additionally, changes the `webpack.config.prod.js` to use cross-env resolution for the paths that are considered external.

## Changes/Tasks

- [X] Changed code

## Motivation and Context

Fixes #1094 
Fixes #1122
Fixes #1123

## Types of changes

- [ ] Refactoring/add tests (refactoring or adding test which isn't a fix or add a feature)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have updated the documentation accordingly
- [X] I have updated the CHANGELOG with a summary of my changes
- [X] My changes have tests around them

### CODE REVIEW

**Comment by SleeplessByte** [comment]
I've not added tests yet, and not thoroughly tested this in general. 
- This works in my project.
- Opened the PR as tracking PR and accepting comments / ideas before tests are done.

**Comment by tannerlinsley** [comment]
This looks great to me. Let me know when you're ready to merge. I am!

**Comment by SleeplessByte** [comment]
@tannerlinsley I just want to add a few tests to cover this in perpetuity. 

Currently making sure this all works with nested paths et cetera, adding tests:
- both types of directory separators
- using .resolve in location (absolute, using system separators)
- using .join in location (relative, but correct)
- using hardcoded `/` in location (relative, and incorrect)
- nested paths (both \\ and /)

**Comment by tannerlinsley** [comment]
Awesome!

**Comment by SleeplessByte** [comment]
FWIW: I tested out nested paths etc; these all work as intended.

` yarn build`  still fails, probably similar issue and not related to this plugin :)

> Failed exporting HTML for URL blog/post/1 (../src/containers/Post):
   Cannot convert undefined or null to object
> - Function.keys
>
> - Routes.js:38 keys
>   [site-name]/[react-static]/src/browser/components/Routes.js:38:1
    4

**Comment by SleeplessByte** [comment]
**:warning: Don't merge yet ⚠️**

Does not yet solve the build issue on windows.

File: packages/react-static/src/utils/chunkBuilder.js [hunk 1]
```diff
@@ -1,44 +1,35 @@
...
-    .replace(path.extname(filename), '') // extension
-    .replace(new RegExp(`[${path.sep}]`, 'g'), '-') // slash to -
+import { escapeRegExp } from './'
 
-  if (chunkName[0] === '-') {
-    return chunkName.substr(1)
-  }
+// Instead of using path.sep, we always want to test for all of them. This makes
+// the tests consistent and means we can write tests with either separator
+const escapedPathSeps = escapeRegExp(`${path.win32.sep}${path.posix.sep}`)
```
Comment (tannerlinsley) [inline packages/react-static/src/utils/chunkBuilder.js]: Genius

**Comment by tannerlinsley** [comment]
This is where the static info is passed into the client bundle: https://github.com/nozzle/react-static/blob/master/packages/react-static/src/bootstrapApp.js#L23-L27

The export process requires the bundle (which is just a commonjs webpack bundle) and calls this function with the siteData, which is then pushed throughout the app via react context.

It's a shame we have to do it this way, but React context instances don't survive across bundles.

**Comment by tannerlinsley** [comment]
The actual context instance lives here: https://github.com/nozzle/react-static/blob/master/packages/react-static/src/browser/context/staticInfoContext.js

If the staticInfo context isn't there, then it probably means it's not being passed to the bundle function in export here: https://github.com/nozzle/react-static/blob/master/packages/react-static/src/static/exportRoute.js#L111

Or, it's not being properly embedded into `window.__routeInfo` here: https://github.com/nozzle/react-static/blob/master/packages/react-static/src/static/components/BodyWithMeta.js#L8

Any thoughts?

**Comment by SleeplessByte** [comment]
@tannerlinsley For funsies I've changed `sharedHashesByProp` online line 38 of `Routes.js`:

```diff
        // Hydrate sharedDataByHash with the embedded routeInfo
-       Object.keys(sharedHashesByProp).forEach(propKey => {
+       Object.keys(sharedHashesByProp || {}).forEach(propKey => {
          sharedDataByHash[sharedHashesByProp[propKey]] = sharedData[propKey]
        })
```

Just so it would pass this part (I did not put any `sharedData` in the config, so this is fine. It should have been an empty hash if the resolution went correctly). However, now it's saying my _static pages_ are suspending (coming from source-filesystem).

I'm a bit at a loss.


Currently looking through the files you just linked.

**Comment by tannerlinsley** [comment]
Let me pull in your PR and try it out.

**Comment by SleeplessByte** [comment]
In order to reproduce:
- pull in the PR
- go into `react-static/packages/react-static`
- yarn build
- go into `react-static/packages/react-static-plugin-source-filesystem`
- yarn build

Create a new project with the basic template
- edit `static.config.js`
  - comment out the dynamic blog post data (so you only have the static pages left)
  - maxThreads: 1 (so all routes are rendered after one another and you can log stuff in-between)

**Comment by SleeplessByte** [comment]
Alright. More information!

I've gone ahead and tried to figure out _where_ exactly it starts losing information. So I logged after the [line you linked from `exportRoute`](https://github.com/nozzle/react-static/blob/master/packages/react-static/src/static/exportRoute.js#L111):

```javascript
{ template: '../src/pages/404.js',
  sharedHashesByProp: {},
  data: {},
  path: '404',
  sharedData: {},
  siteData: {} }

{ template: '../src/pages/about.js',
  sharedHashesByProp: {},
  data: {},
  path: 'about',
  sharedData: {},
  siteData: {} }

{ template: '../src/pages/blog.js',
  sharedHashesByProp: {},
  data: {},
  path: 'blog',
  sharedData: {},
  siteData: {} }

{ template: '../src/pages/index.js',
  sharedHashesByProp: {},
  data: {},
  path: '/',
  sharedData: {},
  siteData: {} }
```

At this point it's all good!

**Comment by tannerlinsley** [comment]
Awesome! Yeah, once you know the data pipeline, it's relatively easy to track.

**Comment by SleeplessByte** [comment]
@tannerlinsley You might be able to help me futher. 

Given the following:
- From my comment above we know that [it is being passed to the bundle in `exportRoute`](https://github.com/nozzle/react-static/blob/master/packages/react-static/src/static/exportRoute.js#L111).
- It's supposed to pre-set the `window` variable [here](https://github.com/nozzle/react-static/blob/master/packages/react-static/src/static/components/BodyWithMeta.js#L8) (as you linked).
- This is called in the `makeBodyWithMeta`:
  ```javascript
  const DocumentHtml = renderToStaticMarkup(
    <DocumentTemplate
      Html={await makeHtmlWithMeta(state)}
      Head={await makeHeadWithMeta(state)}
      Body={await makeBodyWithMeta(state)}
      state={state}
    >
      <div id="root" dangerouslySetInnerHTML={{ __html: appHtml }} />
    </DocumentTemplate>
  )
  ```
- The error happens in the `Routes` component, because nothing comes in via the hook. The `RoutesComponent` is rendered inside `renderToStringAndExtract`:
  ```javascript
   const renderToStringAndExtract = comp => {
    // Rend the app to string!
    const appHtml = renderToString(comp)

    ...
  ```

Help me out with understanding:

1. Now observe that `renderToStringAndExtract` is called here in `exportRoute`:
    ```javascript
    appHtml = renderToStringAndExtract(RenderedComp)
    ```
2. This is _after_ the [line 111](https://github.com/nozzle/react-static/blob/master/packages/react-static/src/static/exportRoute.js#L111) where the bundle is set in `Comp`
3. `Comp` is turned into `FinalComp` (to report chunks)
4. `FinalComp` is renamed to `RenderedComp`

This means that the original `Comp` should have been called like this: `Comp(embeddedRouteInfo)` (✔️)

5. But now we call `renderToStringAndExtract` _before_ `DocumentHtml` is even defined. So `window` can not be set-up, right?

How is it supposed to get the context if there is no body with meta yet?

**Comment by tannerlinsley** [comment]
Hopefully I can lend some insight here. I may repeat myself too, just to be thorough :) Bare with me.

- The static info is necessary to both the static export process *and* the client runtime
- The static info is delivered to both of these environments 2 different ways. I am pretty sure we're discussing the static export phase here :)
- For static export, the static info is passed to the application bundle function here: https://github.com/nozzle/react-static/blob/master/packages/react-static/src/static/exportRoute.js#L111
- `Comp` is now a new component (with the staticInfo embedded via closure) and will supply the static info dato to the context provider when rendered: https://github.com/nozzle/react-static/blob/master/packages/react-static/src/bootstrapApp.js#L23
- The static export rendering process is a two-stage one. One stage for rendering application code (which has already been supplied the static info) and finally the Document shell this is also rendered to string after everything has been extracted from the application code.

**Comment by tannerlinsley** [comment]
You asked about the `bodyWithMeta` part. Here goes!

- `bodyWithMeta` is responsible for inlining the `routeInfo` (which contains all of the static info as well) into the HTML of the rendered page.
- While it *is* in the rendered page, it (maybe deceptively) is *not* what is supplying data to the static export phase.
- It's responsibility is to make the client bootstrap phase a synchronous and fast operation. When the client mounts, it looks for the landing page's routeInfo/staticData on `window` and uses it to rehydrate the client-side data cache. This way react can mount and immediately rehydrate the HTML without displaying any loading indicators.

**Comment by SleeplessByte** [comment]
Makes sense. In other words, it allows for instant hydration!

Okay, that means that the issue is still with the hook; and thus somewhere the data is not correctly passed to the component. 

I'm no longer certain it's a pathing issue; but it could well be a cross-env issue! I think the other error (suspending component) is a _side-effect_ from the data not being present. No data, so it will probably asynchronously try to load the data still => suspend.

**Comment by tannerlinsley** [comment]
Correct. During static export, the data is supplied synchronously so as to not trigger suspense.

**Comment by tannerlinsley** [comment]
Another possibility is that the static info context is not being externalized during webpack bundling. This would effectively result in 2 copies of the static info context instance: a bundled one, and one that is instantiated during export. This would also conveniently be a *slient* error...

You could try searching the generated static bundle `static-app.js` for the context created in `staticInfoContext.js`. If it is in fact bundled in there, then it's an externalizing bug.

**Comment by tannerlinsley** [comment]
Again, if that's the bug, then it's a cross-env one like you're thinking.

**Comment by SleeplessByte** [comment]
> You could try searching the generated static bundle static-app.js for the context created in staticInfoContext.js. If it is in fact bundled in there, then it's an externalizing bug.

What exactly am I looking for? I see `static-app.js` in my artifacts. It contains bundle 47 which is `staticInfoContext`:
```javascript
Object.defineProperty(exports, "staticInfoContext", {
  enumerable: true,
  get: function get() {
    return _staticInfoContext["default"];
  }
});
exports.useStaticInfo = void 0;

var _react = __webpack_require__(0);

var _staticInfoContext = _interopRequireDefault(__webpack_require__(47));

var useStaticInfo = function useStaticInfo() {
  return (0, _react.useContext)(_staticInfoContext["default"]);
};

exports.useStaticInfo = useStaticInfo;

/***/ }),
/* 47 */
/***/ (function(module, exports, __webpack_require__) {

"use strict";
ar _interopRequireDefault = __webpack_require__(6);

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports["default"] = void 0;

var _react = _interopRequireDefault(__webpack_require__(0)); // eslint-disable-next-line


var context = _react["default"].createContext({});

if (typeof document !== 'undefined') {
  context = _react["default"].createContext(window.__routeInfo);
}

var _default = context;
exports["default"] = _default;
```

...Which is the code to create the context, aka the hook.

This code is minified inside `vendors~main.hash.js`:
```javascript
function(e, t, n) {
    "use strict";
    var r = n(2);
    Object.defineProperty(t, "__esModule", {
        value: !0
    }), Object.defineProperty(t, "staticInfoContext", {
        enumerable: !0,
        get: function() {
            return i.default
        }
    }), t.useStaticInfo = void 0;
    var o = n(0),
        i = r(n(103));
    t.useStaticInfo = function() {
        return (0, o.useContext)(i.default)
    }
},
function(e, t, n) {
    "use strict";

    function r(e) {
        return (r = "function" == typeof Symbol && "symbol" == typeof Symbol.iterator ? function(e) {
            return typeof e
        } : function(e) {
            return e && "function" == typeof Symbol && e.constructor === Symbol && e !== Symbol.prototype ? "symbol" : typeof e
        })(e)
    }

    function o(e) {
        return (o = "function" == typeof Symbol && "symbol" === r(Symbol.iterator) ? function(e) {
            return r(e)
        } : function(e) {
            return e && "function" == typeof Symbol && e.constructor === Symbol && e !== Symbol.prototype ? "symbol" : r(e)
        })(e)
    }
    n.r(t);
    var i = n(0),
        a = n.n(i),
        u = (n(111), n(12), n(9)),
        l = n.n(u),
        c = n(47),
        s = n.n(c);


...

function(e, t, n) {
      "use strict";
      var r = n(2);
      Object.defineProperty(t, "__esModule", {
          value: !0
      }), t.default = void 0;
      var o = r(n(0)),
          i = o.default.createContext({});
      "undefined" != typeof document && (i = o.default.createContext(window.__routeInfo));
      var a = i;
      t.default = a
  }
```

**Comment by tannerlinsley** [comment]
Okay. It's okay that it's bundled inside the `vendors.main.js` file. That's for the client.

The fact that it's inside the static bundle is very bad though and confirms my hunch. Webpack is bundling the `staticInfoContext.js` file in the `node` stage (the one that produces `static-app.js`). 

So now the question is, why would it be externalizing that file in my environment, and not yours?

**Comment by tannerlinsley** [comment]
Do you see anything fishy here? https://github.com/nozzle/react-static/blob/master/packages/react-static/src/static/webpack/webpack.config.prod.js#L165-L179

**Comment by SleeplessByte** [comment]
Ah; gimme a minute or three. I'll be back with either a fish on a hook or a single tear.

**Comment by SleeplessByte** [comment]
🐟 🦈

**Comment by SleeplessByte** [comment]
@tannerlinsley let's wait for CI; Amended CHANGELOG.md and the description of this PR.

(🎉 🎉 🎉)

There might be more cross-env issues in other plugins, but at least the starter works again. Feel free to ping/tag me whenever you hit one!

**Comment by tannerlinsley** [comment]
Curiously, are you formatting with the `yarn format` prettier command?

**Comment by SleeplessByte** [comment]
I think it automatically calls that in my IDE

**Comment by tannerlinsley** [comment]
Looks like the only thing that needs to be updated is the xml snapshots, which are actually updated in master. Going to merge and go from there!

**Comment by tannerlinsley** [comment]
For posterity:

This is likely one of the best PR's and Github interactions I have ever had.

**Comment by SleeplessByte** [comment]
Thanks for spending the time explaining how all the moving parts work together!

> Looks like the only thing that needs to be updated is the xml snapshots, which are actually updated in master. Going to merge and go from there!

Yeah I saw those tests fail -- is that because of a change I made? I didn't touch the XML package so I found it weird. On the other hand; it's of course building a sitemap and I changed paths :P

**Comment by tannerlinsley** [comment]
My pleasure!

**Comment by tannerlinsley** [comment]
I updated the XML code in another PR, but not the snapshots.

**Comment by tannerlinsley** [comment]
Code is now available in the 7.0.8 release!

🎉🎉🎉

**Comment by digitalkaoz** [comment]
@SleeplessByte did you test building the site to an absolute path (e.g. `/tmp/out`)? Its needed for building in Lambda...https://github.com/nozzle/react-static/blob/master/docs/guides/aws-lambda.md

**Comment by LukeStanislaus** [comment]
Hi, I'm still getting the #1122 error in the 7.0.9 release. I'm running through cmd.exe on windows:
image
This is from a completely fresh project. I was able to get it working using the WSL, however. I think that the error is related to cross-env issues.

**Comment by SleeplessByte** [comment]
Sitenote: 

> Uncaught SyntaxError: The URL 'http:/[http//localhost]:8080' is invalid

Need to look at this weird mangled hot loading webpack-dev-server url

@digitalkaoz no I did not. Let me know if that currently breaks or not. I'm happy to figure that one out too if it doesnt work!

@LukeStanislaus you're on 7.0.5

**Comment by SleeplessByte** [comment]
image

Ha. It's correct once and wrong once 😓 😅

**Comment by SleeplessByte** [comment]
When I look at the [documentation](https://webpack.js.org/guides/hot-module-replacement/) for hot module replacement, it seems the current webpack.dev config file is outdated. I'll open another PR so you can check it out.

**Comment by digitalkaoz** [comment]
Hey, you can Check it yourself (im on vacation). Just build to `/tmp/foo`
using the paths.* Config option

Thanks
Robert



Derk-Jan Karrenbeld <notifications@github.com> schrieb am Di., 16. Apr.
2019, 17:58:

**Comment by FayeB** [comment]
This issue still seems to be happening in August.  Using a Windows ten laptop with latest downloads from yarn.
Using React-static 7.1.0
Also getting this peculiar message when I just enter react-static but not sure if its related.:

init().catch(e => {
      ^

TypeError: Cannot read property 'catch' of undefined
    at Object.<anonymous> (C:\Users\msfay\AppData\Local\Yarn\Data\global\node_modules\react-static\bin\react-static:5:7)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

**Comment by SleeplessByte** [comment]
@FayeB can you open a new issue for that last thing?
